FROM amd64/python:3.7-slim-buster

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        libcurl4-openssl-dev \
        libboost-python-dev \
        libgtk2.0-dev \
        libgl1

COPY requirements.txt ./
RUN pip install -r requirements.txt

ADD /app/ .

# Expose the port
EXPOSE 5012

CMD [ "python3", "-u", "./main.py" ]